### ISSUE TITLE
Mahdollisuus asettaa CACL kun viedään tiedostoja

### ISSUE THREAD

**Issue by esalep** [CommunityHiQ/Frends.Community.AWS#13]
Joissain tapauksissa riippuen AWS S3 konfiguraatioista olisi hyvä pystyä määrittelemään vietävälle objektille CACL. 

https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/P_Amazon_S3_Model_PutObjectRequest_CannedACL.htm

Tämä vaatisi CannedACL propertyn asettamisen UploadFileToS3 / PutObjectRequest konstruktorissa.

**Comment by RikuVirtanen** [comment]
Fixed: Now it is possible to add CannedACL property to the task
